services:

  postgres:
    restart: always
    image: postgres
    env_file:
      - .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    user: "${UID}:${GID}"
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - postgres

  madr:
    image: madr
    build: .
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  pgdata:

networks: 
  postgres:
    driver: bridge
